name: 'Update CLA Gist'

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'policies/CLA.md'

jobs:

  update-gist:
    if: github.repository == 'commonhaus/foundation'
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v6

    - name: Update gist
      env:
        GH_TOKEN: ${{ secrets.CLA_GIST_WRITE_PAT }}
      run: |
        # update gist with specific project data
        while IFS=$'\t' read -r name entity gist _; do
          echo "Project Name:  $name  " > tmp.md
          echo "Project Entity: $entity  " >> tmp.md
          echo "" >> tmp.md
          cat policies/CLA.md >> tmp.md

          gh gist edit $gist -f CLA.md tmp.md
        done < <(yq e '.project-cla[] | [.name, .entity, .gist] | @tsv' .github/project-cla.yaml)


